# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Tie-Reduce`
	:runtime-requirement    [ :on "perl 5.006001"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.47"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

